controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5
      - arm_joint_6
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_right_finger_bottom_joint
initial:  # Define initial robot poses.
  - group: arm
    pose: home
  - group: gripper
    pose: opened