obstacle_range: 3.0
raytrace_range: 3.5

robot_base_frame: base_footprint
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

footprint: [[-0.17, -0.18], [-0.17, 0.22], [0.17, 0.22], [0.17, -0.18]]
footprint_padding: 0.0


inflation_radius: 0.1
cost_scaling_factor: 0.2
resolution: 0.05


obstacle_range: 2.0
max_obstacle_height: 2.0
min_obstacle_height: 0.0

map_type: costmap
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, sensor_frame: laser_link}

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacle_layer:
    observation_sources: scan rgbd
    scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, sensor_frame: laser_link}
    rgbd: {data_type: PointCloud2, topic: /rtabmap/cloud_map, marking: true, clearing: true}

inflation_layer:
    inflation_radius: 0.25






