obstacle_range: 3.0
raytrace_range: 3.5

robot_base_frame: base_footprint
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

footprint: [[-0.17, -0.18], [-0.17, 0.22], [0.17, 0.22], [0.17, -0.18]]
footprint_padding: 0.0


inflation_radius: 0.2
cost_scaling_factor: 0.2
resolution: 0.05


obstacle_range: 2.0
max_obstacle_height: 2.0
min_obstacle_height: 0.0

map_type: costmap
observation_sources: rgbd #scan
rgbd: {data_type: PointCloud2, topic: /realsense/depth/color/points, marking: true, clearing: true, sensor_frame: realsense_link} 
#scan: {data_type: LaserScan, topic: /laser_scan, marking: true, clearing: true, sensor_frame: laser_link}
#layer definitions
#static:
#    map_topic: /map
#    subscribe_to_updates: true

obstacle_layer:
    observation_sources: rgbd #scan
    rgbd: {data_type: PointCloud2, topic: /realsense/depth/color/points, marking: true, clearing: true, sensor_frame: realsense_link} 
    #scan: {data_type: LaserScan, topic: /laser_scan, marking: true, clearing: true, sensor_frame: laser_link}
inflation_layer:
    inflation_radius: 0.5






