<?xml version="1.0"?>
<robot name="beam" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constant for paul base -->
  <xacro:property name="mass" 			value="20.0" />
  <xacro:property name="base_width" 		value="0.64135" />
  <xacro:property name="base_height"		value="0.85027" /> <!-- Without wheels -->
  <xacro:property name="base_length"		value="1.1303" />
  <xacro:property name="base_pose_z"		value="${ground_to_base_z}" />
  <xacro:property name="wheel_to_base_z" 	value="0.08827" />
  <xacro:property name="ground_to_base_z"	value="${wheel_to_base_z + wheel_radius}" />

  <!-- Common wheels parameters -->
  <xacro:property name="wheel_diameter"		value="0.14732" />
  <xacro:property name="wheel_radius"		value="${wheel_diameter/2}"/>
  <xacro:property name="wheel_thickness"	value="0.03"/>
  <xacro:property name="wheel_mass"		value="0.200"/>
  <xacro:property name="front_to_rear_wheels_x"	value="0.84056"/>
  <xacro:property name="front_right_left_y"	value="0.3302"/>
  <xacro:property name="rear_right_left_y"	value="0.5715"/>

  <!-- Constant for driven wheels -->
    <!-- Right wheel parameters -->
  <xacro:property name="wheel_R_pose_x"		value="${-front_to_rear_wheels_x/2}"/>
  <xacro:property name="wheel_R_pose_y"		value="${-rear_right_left_y/2}"/> 
  <xacro:property name="wheel_R_pose_z"		value="${-wheel_radius}"/>
  <xacro:property name="wheel_R_rot_x"   	value="0.0000"/>
  <xacro:property name="wheel_R_rot_y"   	value="0.0000"/>
  <xacro:property name="wheel_R_rot_z"   	value="0.0000"/>
    <!-- Left wheel parameters -->
  <xacro:property name="wheel_L_pose_x"		value=" ${wheel_R_pose_x}"/>
  <xacro:property name="wheel_L_pose_y"		value="${-wheel_R_pose_y}"/>
  <xacro:property name="wheel_L_pose_z"		value=" ${wheel_R_pose_z}"/>
  <xacro:property name="wheel_L_rot_x"		value=" ${wheel_R_rot_x}"/>
  <xacro:property name="wheel_L_rot_y"		value=" ${wheel_R_rot_y}"/>
  <xacro:property name="wheel_L_rot_z"		value=" ${wheel_R_rot_z}"/>

  <!-- Constant for caster wheels -->
    <!-- Right caster wheel parameters -->
  <xacro:property name="caster_R_pose_x"	value="${front_to_rear_wheels_x/2}"/>
  <xacro:property name="caster_R_pose_y"	value="${-front_right_left_y/2}"/> 
  <xacro:property name="caster_R_pose_z"	value="${-wheel_radius}"/>
  <xacro:property name="caster_R_rot_x"   	value="0.0000"/>
  <xacro:property name="caster_R_rot_y"   	value="0.0000"/>
  <xacro:property name="caster_R_rot_z"   	value="0.0000"/>
    <!-- Left caster wheel parameters -->
  <xacro:property name="caster_L_pose_x"	value=" ${caster_R_pose_x}"/>
  <xacro:property name="caster_L_pose_y"	value="${-caster_R_pose_y}"/>
  <xacro:property name="caster_L_pose_z"	value=" ${caster_R_pose_z}"/>
  <xacro:property name="caster_L_rot_x"		value=" ${caster_R_rot_x}"/>
  <xacro:property name="caster_L_rot_y"		value=" ${caster_R_rot_y}"/>
  <xacro:property name="caster_L_rot_z"		value=" ${caster_R_rot_z}"/>


    <!-- Left caster wheel parameters -->

  <!-- Included files -->
  <xacro:include filename="$(find paul_description)/urdf/wheel.urdf.xacro" />
  <xacro:include filename="$(find paul_description)/urdf/caster.urdf.xacro" />
  <xacro:include filename="$(find paul_description)/urdf/paul.gazebo.xacro" />
  <xacro:include filename="$(find paul_description)/urdf/lidar.urdf.xacro" />

  <!-- BASE FOOTPRINT -->
  <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin -->
  <link name="base_footprint"/>

  <!-- BASE_LINK (only static pieces) -->
  <link name="base_link">
    <inertial>
      <mass value="24.265" />
      <!-- Position of center of mass -->
      <origin xyz="-0.176 0.0 0.203" rpy="0 0 0" />
      <!-- Moment of inertia around center of mass -->
      <inertia  ixx="3.681" ixy="0.0"  ixz="-0.168"  
                iyy="4.665"  iyz="0.0"  
                izz="3.867" /> 
    </inertial>

    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <mesh filename="package://paul_description/meshes/shopping-cart-without-wheels.stl"/>
      </geometry>
      <material name="white"/>
    </visual>

    <collision>
      <origin xyz="0.0 0.0 ${base_height/2}" rpy="0.0 0.0 0.0"/>
      <geometry>
        <!--box size ="${base_length} ${base_width} ${base_height}" /-->
        <mesh filename="package://paul_description/meshes/shopping-cart-without-wheels.stl"/>
      </geometry>
    </collision>

  </link>

  <joint name="footprintBase" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0.0 0.0 ${ground_to_base_z}" rpy="0 0 0"/>
  </joint>

  <!-- IMU -->
  <link name="imu_link"/>

  <joint name="baseIMU" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Cameras -->
  <link name="rgb1_link" >
    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size ="0.03 0.03 0.03" />
      </geometry>
      <material name="black"/>
    </visual>
  </link>
  <link name="rgb2_link"/>

  <joint name="baseRGB1" type="fixed">
    <parent link="base_link"/>
    <child link="rgb1_link"/>
    <origin xyz="0.592 0.0 0.532" rpy="0 0 0"/>
  </joint>

  <joint name="baseRGB2" type="fixed">
    <parent link="base_link"/>
    <child link="rgb2_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- driven wheels -->
    <!-- Right Wheel: "wheel_R_link" and "wheel_R_joint" -->
  <xacro:wheel lr="R" parent="base_link" wheelRadius="${wheel_radius}" wheelLength="${wheel_thickness}" wheelMass="${wheel_mass}" posX="${wheel_R_pose_x}" posY="${wheel_R_pose_y}" posZ="${wheel_R_pose_z}" flipY="1"/>
    <!-- Left Wheel: "wheel_L_link" and "wheel_L_joint" -->
  <xacro:wheel lr="L" parent="base_link" wheelRadius="${wheel_radius}" wheelLength="${wheel_thickness}" wheelMass="${wheel_mass}" posX="${wheel_L_pose_x}" posY="${wheel_L_pose_y}" posZ="${wheel_L_pose_z}" flipY="1"/>

  <!-- caster wheels -->
    <!-- Right caster wheel: "caster_R_link" and "caster_R_joint" -->
  <xacro:caster lr="R" parent="base_link" casterRadius="${wheel_radius}" casterMass="${wheel_mass}" posX="${caster_R_pose_x}" posY="${caster_R_pose_y}" posZ="${caster_R_pose_z}" flipY="1"/>
    <!-- Left caster wheel: "caster_L_link" and "caster_L_joint" -->
  <xacro:caster lr="L" parent="base_link" casterRadius="${wheel_radius}" casterMass="${wheel_mass}" posX="${caster_L_pose_x}" posY="${caster_L_pose_y}" posZ="${caster_L_pose_z}" flipY="1"/>
  
  <!-- Lidar sensor -->
  <xacro:lidar parent="base_link">
    <origin xyz="0.50614 0 0.1" rpy="0 0 0" />
  </xacro:lidar>

</robot>
