<?xml version="1.0"?>
<robot name="beam" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constant for paul base -->
  <xacro:property name="mass" 			value="1.0" />
  <xacro:property name="base_width" 		value="0.64135" />
  <xacro:property name="base_height"		value="0.85027" /> <!-- Without wheels -->
  <xacro:property name="base_length"		value="1.1303" />
  <xacro:property name="base_pose_z"		value="${ground_to_base_z}" />
  <xacro:property name="wheel_to_base_z" 	value="0.08827" />
  <xacro:property name="ground_to_base_z"	value="${wheel_to_base_z + wheel_radius}" />

  <!-- Constant for driven wheels -->
    <!-- Common parameters -->
  <xacro:property name="wheel_diameter"		value="0.14732" />
  <xacro:property name="wheel_radius"		value="${wheel_diameter/2}"/>
  <xacro:property name="wheel_thickness"	value="0.055"/>
  <xacro:property name="front_to_rear_wheels_x"	value="0.84056"/>
  <xacro:property name="front_right_left_y"	value="0.3302"/>
  <xacro:property name="rear_right_left_y"	value="0.5715"/>

    <!-- Right wheel parameters -->
  <xacro:property name="wheel_R_pose_x"		value="${-front_to_rear_wheels_x/2}"/>
  <xacro:property name="wheel_R_pose_y"		value="${-rear_right_left_y/2}"/> 
  <xacro:property name="wheel_R_pose_z"		value="${-wheel_radius}"/>
  <xacro:property name="wheel_R_rot_x"   	value="0.0000"/>
  <xacro:property name="wheel_R_rot_y"   	value="0.0000"/>
  <xacro:property name="wheel_R_rot_z"   	value="0.0000"/>

    <!-- Left wheel parameters -->
  <xacro:property name="wheel_L_pose_x"		value=" ${wheel_R_pose_x}"/>
  <xacro:property name="wheel_L_pose_y"		value="${-wheel_R_pose_y}"/>
  <xacro:property name="wheel_L_pose_z"		value=" ${wheel_R_pose_z}"/>
  <xacro:property name="wheel_L_rot_x"		value=" ${wheel_R_rot_x}"/>
  <xacro:property name="wheel_L_rot_y"		value=" ${wheel_R_rot_y}"/>
  <xacro:property name="wheel_L_rot_z"		value=" ${wheel_R_rot_z}"/>

  <!-- Included files -->
  <xacro:include filename="$(find paul_description)/urdf/wheel.urdf.xacro" /> 

  <!-- BASE FOOTPRINT -->
  <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin -->
  <link name="base_footprint"/>

  <!-- BASE_LINK (only static pieces) -->
  <link name="base_link">
    <inertial>
      <mass value="1" />
      <inertia  ixx="0.001" ixy="0.0"  ixz="0.0"  
                iyy="0.001"  iyz="0.0"  
                izz="0.001" /> 
    </inertial>

    <visual>
      <origin xyz="0.0 0.0 ${-ground_to_base_z}" rpy="0.0 0.0 0.0"/>
      <geometry>
        <mesh filename="package://paul_description/meshes/shopping-cart-without-wheels.stl"/>
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <origin xyz="0.0 0.0 ${base_height}" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size ="${base_length} ${base_width} ${base_height}" />
      </geometry>
    </collision>

  </link>

  <joint name="footprintBase" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0.0 0.0 ${ground_to_base_z}" rpy="0 0 0"/>
  </joint>

  <!-- IMU -->
  <link name="imu_link"/>

  <joint name="baseIMU" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- LiDAR -->
  <link name="lidar_link"/>

  <joint name="baseLidar" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Cameras -->
  <link name="rgb1_link"/>
  <link name="rgb2_link"/>

  <joint name="baseRGB1" type="fixed">
    <parent link="base_link"/>
    <child link="rgb1_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <joint name="baseRGB2" type="fixed">
    <parent link="base_link"/>
    <child link="rgb2_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Robot arm -->
  <link name="arm_j1_link"/>
  <link name="arm_j2_link"/>
  <link name="arm_j3_link"/>


  <joint name="baseArm_j1" type="fixed">
    <parent link="base_link"/>
    <child link="arm_j1_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <joint name="arm_j1_j2" type="fixed">
    <parent link="arm_j1_link"/>
    <child link="arm_j2_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <joint name="arm_j2_j3" type="fixed">
    <parent link="arm_j2_link"/>
    <child link="arm_j3_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Realsense D455 Camera --> 
  <!--xacro:realsense_d455_sensor parent="head_link" name="realsense" >
    <origin xyz="${Realsense_pose_x} ${Realsense_pose_y} ${Realsense_pose_z}" rpy="${Realsense_rotation_x} ${Realsense_rotation_y} ${Realsense_rotation_z}"/>
  </xacro:realsense_d455_sensor-->

  <!-- wheels --><!--
  <xacro:wheel fb="F" lr="R" parent="base_link" wheelRadius="${Right_wheel_radius}" wheelLength="${Right_wheel_thickness}" wheelMass="${mass/2}" posX="${Right_wheel_pose_x}" posY="${Right_wheel_pose_y}" posZ="${Right_wheel_pose_z}" flipY="1"/>
  <xacro:wheel fb="F" lr="L" parent="base_link" wheelRadius="${Left_wheel_radius}" wheelLength="${Left_wheel_thickness}" wheelMass="${mass/2}" posX="${Left_wheel_pose_x}" posY="${Left_wheel_pose_y}" posZ="${Left_wheel_pose_z}" flipY="1"/-->

</robot>
